# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
TicketCategory.create(:title=>'Technical')
TicketCategory.create(:title=>'New hardware Request')
TicketCategory.create(:title=>'Internet', :ticket_category_id=>1)
TicketCategory.create(:title=>'Software', :ticket_category_id=>1)
TicketCategory.create(:title=>'Slow internet browsing', :ticket_category_id=>3)
TicketCategory.create(:title=>'Link not working', :ticket_category_id=>3)
TicketCategory.create(:title=>'Skype Issue', :ticket_category_id=>3)
TicketCategory.create(:title=>'Download a software', :ticket_category_id=>3)
TicketCategory.create(:title=>'Server Issues', :ticket_category_id=>3)
TicketCategory.create(:title=>'Password reset', :ticket_category_id=>3)
TicketCategory.create(:title=>'Configuration of new email ID', :ticket_category_id=>3)
TicketCategory.create(:title=>'NXVT & NXB issues', :ticket_category_id=>3)
TicketCategory.create(:title=>'other', :ticket_category_id=>3)
TicketCategory.create(:title=>'Windows', :ticket_category_id=>4)
TicketCategory.create(:title=>'System is unresponsive', :ticket_category_id=>4)
TicketCategory.create(:title=>'Install a software', :ticket_category_id=>4)
TicketCategory.create(:title=>'Creation of a virtual machine', :ticket_category_id=>4)
TicketCategory.create(:title=>'Other', :ticket_category_id=>4)
TicketCategory.create(:title=>'Processors', :ticket_category_id=>2)
TicketCategory.create(:title=>'Rams', :ticket_category_id=>2)
TicketCategory.create(:title=>'Harddisk', :ticket_category_id=>2)
TicketCategory.create(:title=>'Keyboards', :ticket_category_id=>2)
TicketCategory.create(:title=>'Mouse', :ticket_category_id=>2)
TicketCategory.create(:title=>'Head Sets', :ticket_category_id=>2)
TicketCategory.create(:title=>'LCD', :ticket_category_id=>2)
TicketCategory.create(:title=>'Head Phones', :ticket_category_id=>2)
TicketCategory.create(:title=>'Other', :ticket_category_id=>2)
TicketStatus.create( :title=>'New' )
TicketStatus.create( :title=>'In Progress' )
TicketStatus.create( :title=>'Solved' )
TicketStatus.create( :title=>'On Hold' )
TicketType.create( :title=>'Hdw' )
TicketType.create( :title=>'Op' )
UserRole.create( :title=>'MIS'  )
UserRole.create( :title=>'noc' )
user_role= UserRole.create( :title=>'admin' )
UserRole.create( :title=>'MIS_admin' )
UserRole.create( :title=>'noc_admin' )
UserRole.create( :title=>'TM' )
UserRole.create( :title=>'TL' )
UserRole.create( :title=>'DM' )
User.create(:username=>'kamal', :password=>'8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', :full_name=>'Kamal', :user_role_id=>user_role.id)
TicketPriority.create( :title=>'Normal' )
TicketPriority.create( :title=>'High' )
TicketPriority.create( :title=>'Low' )
